name: workshop-organizer

services:

  app:
    image: vbuyakov/ocr-java-angular-project-6-back:latest
    ports:
      - "${APP_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
    depends_on:
      init-db:
        condition: service_completed_successfully

  db:
    image: ${POSTGRES_IMAGE}
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  init-db:
    image: ${POSTGRES_IMAGE}
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    volumes:
      - ./db:/scripts:ro
    working_dir: /scripts
    command: ["/bin/bash", "/scripts/init_db.sh", "/scripts"]
    restart: "no"

volumes:
  postgres_data:
